version: '3.8'

services:
  web:
    build: .
    command: start_dev
    tty: true
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.dev
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev

volumes:
  postgres_data:
