version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.dev
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev

  test:
    build: .
    command: python manage.py test
    volumes:
      - .:/code
    depends_on:
      - db
    env_file:
      - .env.dev

  migrate:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/code
    depends_on:
      - db
    env_file:
      - .env.dev

volumes:
  postgres_data:
